const CartridgeRentActionTypes = {

  FETCH_RENT_LIST_START: 'FETCH_RENT_LIST_START',
  FETCH_RENT_LIST_SUCCESS: 'FETCH_RENT_LIST_SUCCESS',
  FETCH_RENT_LIST_FAILURE: 'FETCH_RENT_LIST_FAILURE'

}

export default CartridgeRentActionTypes;