const CartridgeRentActionTypes = {

  FETCH_RENT_LIST_START: 'FETCH_RENT_LIST_START',
  FETCH_RENT_LIST_SUCCESS: 'FETCH_RENT_LIST_SUCCESS',
  FETCH_RENT_LIST_FAILURE: 'FETCH_RENT_LIST_FAILURE',

  FETCH_FOR_RENT_START: 'FETCH_FOR_RENT_START',
  FETCH_FOR_RENT_SUCCESS: 'FETCH_FOR_RENT_SUCCESS',
  FETCH_FOR_RENT_FAILURE: 'FETCH_FOR_RENT_FAILURE',

  FETCH_RENT_FORM_START: 'FETCH_RENT_FORM_START',
  FETCH_RENT_FORM_SUCCESS: 'FETCH_RENT_FORM_SUCCESS',
  FETCH_RENT_FORM_FAILURE: 'FETCH_RENT_FORM_FAILURE'
}

export default CartridgeRentActionTypes;