const AdminActionTypes = {
  FIRE_EMPLOYEE_START: 'FIRE_EMPLOYEE_START',
  FIRE_EMPLOYEE_SUCCESS: 'FIRE_EMPLOYEE_SUCCESS',
  FIRE_EMPLOYEE_FAILURE: 'FIRE_EMPLOYEE_FAILURE',

  ACTIVATE_EMPLOYEE_START: 'ACTIVATE_EMPLOYEE_START',
  ACTIVATE_EMPLOYEE_SUCCESS: 'ACTIVATE_EMPLOYEE_SUCCESS',
  ACTIVATE_EMPLOYEE_FAILURE: 'ACTIVATE_EMPLOYEE_FAILURE'
}

export default AdminActionTypes;