const employeeActionTypes = {
  FETCH_EMPLOYEES_START: 'FETCH_EMPLOYEES_START',
  FETCH_EMPLOYEES_FAILURE: 'FETCH_EMPLOYEES_FAILURE',
  FETCH_EMPLOYEES_SUCCESS: 'FETCH_EMPLOYEES_SUCCESS'
}

export default employeeActionTypes;