const employeeActionTypes = {
  FETCH_EMPLOYEES_START: 'FETCH_EMPLOYEES_START',
  FETCH_EMPLOYEES_FAILURE: 'FETCH_EMPLOYEES_FAILURE',
  FETCH_EMPLOYEES_SUCCESS: 'FETCH_EMPLOYEES_SUCCESS',

  ADD_EMPLOYEE_START: 'ADD_EMPLOYEE_START',
  ADD_EMPLOYEE_FAILURE: 'ADD_EMPLOYEE_FAILURE',
  ADD_EMPLOYEE_SUCCESS: 'ADD_EMPLOYEE_SUCCESS'
}

export default employeeActionTypes;