const employeeActionTypes = {
  FETCH_EMPLOYEES_START: 'FETCH_EMPLOYEES_START',
  FETCH_EMPLOYEES_FAILURE: 'FETCH_EMPLOYEES_FAILURE',
  FETCH_EMPLOYEES_SUCCESS: 'FETCH_EMPLOYEES_SUCCESS',

  ADD_EMPLOYEE_START: 'ADD_EMPLOYEE_START',
  ADD_EMPLOYEE_FAILURE: 'ADD_EMPLOYEE_FAILURE',
  ADD_EMPLOYEE_SUCCESS: 'ADD_EMPLOYEE_SUCCESS',

  FETCH_ALL_RENTALS_START: 'FETCH_ALL_RENTALS_START',
  FETCH_ALL_RENTALS_SUCCESS: 'FETCH_ALL_RENTALS_SUCCESS',
  FETCH_ALL_RENTALS_FAILURE: 'FETCH_ALL_RENTALS_FAILURE', 

  UPDATE_RENTAL_RETURN_START: 'UPDATE_RENTAL_RETURN_START',
  UPDATE_RENTAL_RETURN_SUCCESS: 'UPDATE_RENTAL_RETURN_SUCCESS',
  UPDATE_RENTAL_RETURN_FAILURE: 'UPDATE_RENTAL_RETURN_FAILURE'
}

export default employeeActionTypes;