const CartridgeActionTypes = {
  FETCH_MOVIES_FOR_DROPDOWN_START: 'FETCH_MOVIES_FOR_DROPDOWN_START',
  FETCH_MOVIES_FOR_DROPDOWN_SUCCESS: 'FETCH_MOVIES_FOR_DROPDOWN_SUCCESS',
  FETCH_MOVIES_FOR_DROPDOWN_FAILURE: 'FETCH_MOVIES_FOR_DROPDOWN_FAILURE',

  ADD_CARTRIDGE_START: 'ADD_CARTRIDGE_START',
  ADD_CARTRIDGE_SUCCESS: 'ADD_CARTRIDGE_SUCCESS',
  ADD_CARTRIDGE_FAILURE: 'ADD_CARTRIDGE_FAILURE',

  FETCH_CARTRIDGES_START: 'FETCH_CARTRIDGES_START',
  FETCH_CARTRIDGES_SUCCESS: 'FETCH_CARTRIDGES_SUCCESS',
  FETCH_CARTRIDGES_FAILURE: 'FETCH_CARTRIDGES_FAILURE',

  FETCH_CARTRIDGE_START: 'FETCH_CARTRIDGE_START',
  FETCH_CARTRIDGE_SUCCESS: 'FETCH_CARTRIDGE_SUCCESS',
  FETCH_CARTRIDGE_FAILURE: 'FETCH_CARTRIDGE_FAILURE',

  EDIT_CARTRIDGE_START: 'EDIT_CARTRIDGE_START',
  EDIT_CARTRIDGE_SUCCESS: 'EDIT_CARTRIDGE_SUCCESS',
  EDIT_CARTRIDGE_FAILURE: 'EDIT_CARTRIDGE_FAILURE',

  UPDATE_CARTRIDGE_START: 'UPDATE_CARTRIDGE_START',
  UPDATE_CARTRIDGE_SUCCESS: 'UPDATE_CARTRIDGE_SUCCESS',
  UPDATE_CARTRIDGE_FAILURE: 'UPDATE_CARTRIDGE_FAILURE'
}

export default CartridgeActionTypes;