const AuthActionTypes = {
  REGISTER_START: 'REGISTER_START',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  
  CHECK_TOKEN_START: 'CHECK_TOKEN_START',
  CHECK_TOKEN_SUCCESS: 'CHECK_TOKEN_SUCCESS',
  CHECK_TOKEN_FAILURE: 'CHECK_TOKEN_FAILURE',
  SAVE_TOKEN: 'SAVE_TOKEN',
  SAVE_USER: 'SAVE_USER' 
}

export default AuthActionTypes;