const ShopUserActionTypes = {
  FETCH_USER_RENTALS_START: 'FETCH_USER_RENTALS_START',
  FETCH_USER_RENTALS_SUCCESS: 'FETCH_USER_RENTALS_SUCCESS',
  FETCH_USER_RENTALS_FAILURE: 'FETCH_USER_RENTALS_FAILURE'
}

export default ShopUserActionTypes;