const AddressActionTypes = {
  FETCH_ADDRESSES_START: 'FETCH_ADDRESSES_START',
  FETCH_ADDRESSES_SUCCESS: 'FETCH_ADDRESSES_SUCCESS',
  FETCH_ADDRESSES_FAILURE: 'FETCH_ADDRESSES_FAILURE',
  
  DEACTIVATE_ADDRESS_START: 'DEACTIVATE_ADDRESS_START',
  DEACTIVATE_ADDRESS_SUCCESS: 'DEACTIVATE_ADDRESS_SUCCESS',
  DEACTIVATE_ADDRESS_FAILURE: 'DEACTIVATE_ADDRESS_FAILURE',
    
  ADD_ADDRESS_START: 'ADD_ADDRESS_START',
  ADD_ADDRESS_SUCCESS: 'ADD_ADDRESS_SUCCESS',
  ADD_ADDRESS_FAILURE: 'ADD_ADDRESS_FAILURE',
  
  NULL_ADDRESSES: 'NULL_ADDRESSES'
}

export default AddressActionTypes;